title:              cheng2
email:              ccstan99@gmail.com
description:        My Personal Learning Journal
author:             cheng2
baseurl:            ""
url:                "https://ccstan99.github.io"

# Social Profiles
github_username:    ccstan99
linkedin_username:  cheng2-tan
twitter_username:  cheng2_tan

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-D2PE2V9SD7 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           20
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge